Storage watcher
filecoin-project/cpp-filecoin pull request #283
Opened 2020-10-14 14:41 UTC by igkrsh

### Description of the Change
Storage watcher is the utility to check the health of each storage. Every storage should send heartbeat, every it's heartbeats interval. Created heartbeat function and scheduler to send it every time period.

### Benefits
Ability to check health of the storgae.

### Possible Drawbacks 
None

### Usage Examples or Tests
LocalStoreTest::storageHealthSuccess

2020-10-15 11:11 UTC, artyom-yurin requested changes

2020-10-15 11:11 UTC, artyom-yurin commented on core/sector_storage/stores/impl/local_store.cpp
> +    local->heartbeat_ = kHeartbeatInterval.count() * 1000 + gen(rng);
We need ~10%
10 seconds * 0.1 = 1 second (max condition)

2020-10-15 11:11 UTC, artyom-yurin commented on core/sector_storage/stores/impl/local_store.hpp
> +        Ticks ticks);
```suggestion
        Ticks ticks = 50);
```

2020-10-15 11:11 UTC, artyom-yurin commented on core/sector_storage/stores/impl/local_store.hpp
> +    ~LocalStoreImpl();
We can try without custom destructor

2020-10-15 11:11 UTC, artyom-yurin commented on core/sector_storage/stores/impl/local_store.cpp
> +    local->heartbeat_ = kHeartbeatInterval.count() * 1000 + gen(rng);
Recheck formula please

2020-10-15 11:26 UTC, turuslan commented on core/sector_storage/stores/impl/local_store.cpp
> +      Ticks ticks = 50) {
Please remove default value from implementation in cpp file

2020-10-15 12:27 UTC, turuslan commented on test/core/sector_storage/stores/local_store_test.cpp
> +}
Add empty line at end of file

2020-10-15 18:06 UTC, turuslan commented on core/sector_storage/stores/impl/local_store.cpp
> +        *fsm_context->getIoContext(), libp2p::protocol::SchedulerConfig{ticks});
`HostContext` is unnecessary, because `getIoContext()` returns same as `context_` and `HostContext` is not used otherwise

2020-10-16 04:42 UTC, turuslan approved these changes

2020-10-16 11:37 UTC, artyom-yurin approved these changes

2020-10-16 11:38 UTC, merged